# Generated by Django 4.1.2 on 2023-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pfp_delete_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='/media/default.jpg', upload_to='media/profile_images'),
        ),
    ]
