# Generated by Django 4.1.2 on 2023-01-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='anime',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='coding',
            old_name='coding',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='crypto',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gaming',
            old_name='game',
            new_name='name',
        ),
    ]
